#!/usr/bin/env python3
"""
DeepCrack → YOLO seg format converter
=====================================
DeepCrack structure:
  deepcrack/
  ├── train_img/      ← 11111.jpg
  ├── train_lab/      ← 11111.png (binary mask, 0/255)
  ├── test_img/       ← 111212-1.jpg
  └── test_lab/       ← 111212-1.png (binary mask, 0/255)

Output (YOLO seg format, ready for ultralytics):
  deepcrack_yolo/
  ├── images/
  │   ├── train/
  │   ├── val/
  │   └── test/
  ├── labels/
  │   ├── train/
  │   ├── val/
  │   └── test/
  └── dataset.yaml

Each .txt label: one line per connected crack instance
  0 x1 y1 x2 y2 ... (normalized polygon, class 0 = crack)

Splits:
  - Train: 80% of train_img (480 images)
  - Val: 20% of train_img (120 images)
  - Test: 100% of test_img (474 images)
"""

import os
import cv2
import numpy as np
import argparse
import shutil
from pathlib import Path
from tqdm import tqdm


CLASS_ID = 0        # single class: crack
MIN_AREA = 50       # minimum pixel area to keep an instance
MIN_POINTS = 6      # minimum polygon points (3 coordinate pairs)


def binary_mask_to_yolo_instances(mask_path: str, img_w: int, img_h: int) -> list[str]:
    """
    Read binary PNG mask → split into instances via connectedComponents
    → convert each to normalized YOLO seg polygon string.
    """
    mask = cv2.imread(mask_path, cv2.IMREAD_GRAYSCALE)
    if mask is None:
        return []

    # Threshold (DeepCrack masks are 0/255)
    binary = (mask > 127).astype(np.uint8)

    # Separate touching cracks into individual instances
    num_labels, labels_map = cv2.connectedComponents(binary)

    label_lines = []
    for label_id in range(1, num_labels):      # 0 = background
        instance = (labels_map == label_id).astype(np.uint8)

        if instance.sum() < MIN_AREA:
            continue

        # Find contours for this instance
        contours, _ = cv2.findContours(
            instance, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE
        )

        for contour in contours:
            if len(contour) < MIN_POINTS // 2:
                continue

            # Flatten and normalize to [0, 1]
            pts = contour.squeeze()
            if pts.ndim == 1:
                pts = pts.reshape(1, 2)

            # Simplify contour slightly to reduce file size
            epsilon = 0.002 * cv2.arcLength(contour, True)
            simplified = cv2.approxPolyDP(contour, epsilon, True).squeeze()
            if simplified.ndim == 1:
                simplified = simplified.reshape(1, 2)
            if len(simplified) < 3:
                simplified = pts

            norm = []
            for x, y in simplified:
                norm.append(x / img_w)
                norm.append(y / img_h)

            if len(norm) < MIN_POINTS:
                continue

            coords_str = " ".join(f"{v:.6f}" for v in norm)
            label_lines.append(f"{CLASS_ID} {coords_str}")

    return label_lines


def process_images(image_list: list[Path], mask_dir: Path, dst_img_dir: Path, dst_lbl_dir: Path, split_name: str):
    """Process a list of images for a specific split."""
    dst_img_dir.mkdir(parents=True, exist_ok=True)
    dst_lbl_dir.mkdir(parents=True, exist_ok=True)

    converted = 0
    skipped = 0

    for img_path in tqdm(image_list, desc=f"  {split_name}", leave=False):
        stem = img_path.stem

        # Find corresponding mask (.png with same stem in mask_dir)
        mask_path = mask_dir / f"{stem}.png"
        if not mask_path.exists():
            skipped += 1
            continue

        # Read image to get dimensions
        img = cv2.imread(str(img_path))
        if img is None:
            skipped += 1
            continue
        h, w = img.shape[:2]

        # Convert mask to YOLO seg labels
        label_lines = binary_mask_to_yolo_instances(str(mask_path), w, h)

        # Copy image
        dst_img_path = dst_img_dir / img_path.name
        shutil.copy2(img_path, dst_img_path)

        # Write label file (even if empty — YOLO needs it)
        dst_lbl_path = dst_lbl_dir / f"{stem}.txt"
        with open(dst_lbl_path, "w") as f:
            f.write("\n".join(label_lines))

        converted += 1

    print(f"  {split_name}: {converted} images converted, {skipped} skipped")
    return converted


def write_dataset_yaml(dst: Path, num_train: int, num_val: int, num_test: int):
    """Write ultralytics-compatible dataset.yaml."""
    yaml_content = f"""# DeepCrack — YOLO seg format
# Auto-generated by convert_deepcrack.py

path: {dst.resolve()}
train: images/train
val:   images/val
test:  images/test

nc: 1
names:
  0: crack

# Stats
# train: ~{num_train} images
# val:   ~{num_val} images
# test:  ~{num_test} images
"""
    with open(dst / "dataset.yaml", "w") as f:
        f.write(yaml_content)
    print(f"\n  dataset.yaml written to {dst / 'dataset.yaml'}")


def verify_conversion(dst: Path):
    """Quick sanity check on converted dataset."""
    print("\n[Verify] Checking converted dataset...")
    issues = 0
    for split in ["train", "val", "test"]:
        img_dir = dst / "images" / split
        lbl_dir = dst / "labels" / split
        if not img_dir.exists():
            continue

        imgs = list(img_dir.glob("*.jpg")) + list(img_dir.glob("*.png"))
        lbls = list(lbl_dir.glob("*.txt"))

        # Check counts match
        if len(imgs) != len(lbls):
            print(f"  [!] {split}: {len(imgs)} images vs {len(lbls)} labels — mismatch!")
            issues += 1
        else:
            print(f"  {split}: {len(imgs)} images ✓")

        # Check a few labels are non-empty
        non_empty = sum(1 for l in lbls if l.stat().st_size > 0)
        empty     = len(lbls) - non_empty
        print(f"    labels with cracks: {non_empty} | empty (no crack): {empty}")

        if non_empty == 0:
            print(f"  [!] {split}: ALL labels are empty — check mask paths!")
            issues += 1

    if issues == 0:
        print("\n  ✓ Dataset looks good!")
    else:
        print(f"\n  ✗ {issues} issue(s) found — check output above.")

    return issues == 0


def main():
    parser = argparse.ArgumentParser(description="Convert DeepCrack to YOLO seg format")
    parser.add_argument(
        "--src",
        type=str,
        default="data/datasets/deepcrack",
        help="Path to deepcrack root dir"
    )
    parser.add_argument(
        "--dst",
        type=str,
        default=None,
        help="Output directory (default: <src>_yolo)"
    )
    parser.add_argument(
        "--verify",
        action="store_true",
        default=True,
        help="Run sanity check after conversion"
    )
    args = parser.parse_args()

    src = Path(args.src).expanduser().resolve()
    dst = Path(args.dst).expanduser().resolve() if args.dst else src.parent / f"{src.name}_yolo"

    print(f"[Convert] Source: {src}")
    print(f"[Convert] Output: {dst}")
    print()

    if not src.exists():
        print(f"ERROR: Source directory not found: {src}")
        return

    # Check and clean output directory if exists
    if dst.exists():
        print(f"[Warning] Output directory exists, clearing: {dst}")
        shutil.rmtree(dst)

    # 1. Process Train split and do 80-20 partition
    train_img_dir = src / "train_img"
    train_lab_dir = src / "train_lab"
    
    if not train_img_dir.exists() or not train_lab_dir.exists():
        print(f"ERROR: Train directories not found under {src}")
        return

    all_train_files = sorted([
        f for f in train_img_dir.iterdir()
        if f.suffix.lower() in ('.jpg', '.jpeg', '.png')
        and ':Zone.Identifier' not in f.name
    ])

    # Deterministic shuffle
    rng = np.random.RandomState(42)
    shuffled_indices = rng.permutation(len(all_train_files))
    
    n_train = int(len(all_train_files) * 0.8)
    
    train_files = [all_train_files[i] for i in shuffled_indices[:n_train]]
    val_files   = [all_train_files[i] for i in shuffled_indices[n_train:]]

    print(f"Total training images: {len(all_train_files)}")
    print(f"  -> Train split: {len(train_files)}")
    print(f"  -> Val split:   {len(val_files)}")

    # 2. Process Test split
    test_img_dir = src / "test_img"
    test_lab_dir = src / "test_lab"
    
    if not test_img_dir.exists() or not test_lab_dir.exists():
        print(f"ERROR: Test directories not found under {src}")
        return

    test_files = sorted([
        f for f in test_img_dir.iterdir()
        if f.suffix.lower() in ('.jpg', '.jpeg', '.png')
        and ':Zone.Identifier' not in f.name
    ])
    print(f"Total test images:     {len(test_files)}")

    # Convert splits
    counts = {}
    counts["train"] = process_images(
        image_list = train_files,
        mask_dir   = train_lab_dir,
        dst_img_dir= dst / "images" / "train",
        dst_lbl_dir= dst / "labels" / "train",
        split_name = "train",
    )
    
    counts["val"] = process_images(
        image_list = val_files,
        mask_dir   = train_lab_dir,
        dst_img_dir= dst / "images" / "val",
        dst_lbl_dir= dst / "labels" / "val",
        split_name = "val",
    )

    counts["test"] = process_images(
        image_list = test_files,
        mask_dir   = test_lab_dir,
        dst_img_dir= dst / "images" / "test",
        dst_lbl_dir= dst / "labels" / "test",
        split_name = "test",
    )

    write_dataset_yaml(dst, counts["train"], counts["val"], counts["test"])

    if args.verify:
        verify_conversion(dst)

    print(f"\n[Done] Converted DeepCrack dataset at: {dst}")


if __name__ == "__main__":
    main()
