#!/usr/bin/env python3
import json
from pathlib import Path

def main():
    src_path = Path("/home/shahin/distill/final_notebooks/04_run_pixel_affinity_kd.ipynb")
    dst_path = Path("/home/shahin/distill/final_notebooks/09_run_combined_affinity_dilated_kd.ipynb")
    
    with open(src_path) as f:
        nb = json.load(f)

    # Update Cell 0 markdown
    nb["cells"][0]["source"] = [
        "# 🚀 Crack-Distill: Combined Spatial Affinity + Foreground-Dilated KD (Seed 42)\n",
        "Fuses the two empirical winners from production runs:\n",
        "1. **Foreground-Dilated Mask-KL** (from `03_dilated`, best OOD +18.7%)\n",
        "2. **4-Directional Spatial Pixel Affinity** (from `04_affinity`, best in-domain 0.5569 Mask mAP50)\n",
        "\n",
        "### Recipe Specifications:\n",
        "* **Student Model**: YOLOv11n-seg (2.84M parameters, 10.2 GFLOPs)\n",
        "* **Teacher Model**: SAM 2 Large (`sam2_hiera_large.pt`, 224M parameters)\n",
        "* **Prompt Type**: Bounding Box Only (offline pre-computed soft logits)\n",
        "* **Temperature**: $\\tau = 3.7769$, Mask KD Weight: $W = 0.9612$, Affinity Weight: $0.5$\n",
        "* **Head Freezing**: Disabled (Full end-to-end training)\n",
        "* **Precision**: FP32 (`amp: false`) for 100% loss stability\n",
        "* **Random Seed**: `42`\n",
        "* **Automated Evaluation**: Evaluates in-domain cropped val and out-of-distribution uncropped val upon completion.\n"
    ]

    # Update Cell 12 (Step 3: Training)
    nb["cells"][12]["source"] = [
        "# ── Step 3: Run Combined Affinity + Dilated KD (exp_combined_affinity_dilated_kd_T3.7769_W0.9612_seed42_150ep) ──\n",
        "import sys\n",
        "sys.path.insert(0, \".\")\n",
        "from pathlib import Path\n",
        "from distillation.kd_trainer import KDSegmentationTrainer\n",
        "from utils.config_loader import load_config, override_config\n",
        "\n",
        "cfg = load_config(\"configs/config.yaml\")\n",
        "EXPERIMENT_NAME = \"exp_combined_affinity_dilated_kd_T3.7769_W0.9612_seed42_150ep\"\n",
        "\n",
        "overrides = {\n",
        "    \"distillation.enabled\": True,\n",
        "    \"distillation.temperature\": 3.7769,\n",
        "    \"distillation.progressive.enabled\": False,\n",
        "    \"distillation.losses.task.weight\": 1.0,\n",
        "    \"distillation.losses.mask_kd.enabled\": True,\n",
        "    \"distillation.losses.mask_kd.weight\": 0.9612,\n",
        "    \"distillation.losses.mask_kd.focused\": True,       # Focuses loss on 8px dilated crack band\n",
        "    \"distillation.losses.affinity.enabled\": True,      # Enforces 4-directional spatial continuity\n",
        "    \"distillation.losses.affinity.weight\": 0.5,\n",
        "    \"distillation.losses.feature.enabled\": False,\n",
        "    \"distillation.losses.boundary.enabled\": False\n",
        "}\n",
        "overrides[\"project.name\"] = \"crack_distill\"\n",
        "overrides[\"project.experiment\"] = EXPERIMENT_NAME\n",
        "overrides[\"project.seed\"] = 42\n",
        "overrides[\"data.datasets\"] = [{\"name\": \"crack500\", \"path\": \"data/datasets/crack500_yolo\", \"format\": \"yolo\"}]\n",
        "overrides[\"teacher.logits_dir\"] = \"data/teacher_logits_box/\"\n",
        "overrides[\"train.epochs\"] = 150\n",
        "overrides[\"train.amp\"] = False\n",
        "\n",
        "cfg = override_config(cfg, overrides)\n",
        "\n",
        "print(f\"=== Starting Run: {EXPERIMENT_NAME} ===\")\n",
        "print(\"Config in effect: Combined Affinity + Dilated Mask-KL, Seed=42, Epochs=150, AMP=False, Freezing=False\")\n",
        "\n",
        "trainer = KDSegmentationTrainer(cfg)\n",
        "trainer.train()\n",
        "print(\"✓ Training completed successfully!\")\n"
    ]

    # Update Cell 13 (Step 4: Evaluation & Leaderboard comparison)
    nb["cells"][13]["source"] = [
        "# ── Step 4: Validate Best Checkpoint & Compare vs. All Baselines ──\n",
        "import glob, json, os\n",
        "from pathlib import Path\n",
        "from ultralytics import YOLO\n",
        "\n",
        "BASELINES = {\n",
        "    \"No-KD Baseline (EXP-10)\": {\"Mask mAP50\": 0.5400, \"Box mAP50\": 0.5970, \"OOD mAP50\": 0.0848},\n",
        "    \"01_seed42 (Locked Baseline)\": {\"Mask mAP50\": 0.5424, \"Box mAP50\": 0.5976, \"OOD mAP50\": 0.0848},\n",
        "    \"03_dilated (Best OOD)\": {\"Mask mAP50\": 0.5387, \"Box mAP50\": 0.5819, \"OOD mAP50\": 0.1007},\n",
        "    \"04_affinity (Spatial Affinity)\": {\"Mask mAP50\": 0.5348, \"Box mAP50\": 0.5831, \"OOD mAP50\": 0.0831},\n",
        "    \"05_multiscale (Best In-Domain/Box)\": {\"Mask mAP50\": 0.5485, \"Box mAP50\": 0.6001, \"OOD mAP50\": 0.0872},\n",
        "    \"06_layerkd (Best mAP50-95)\": {\"Mask mAP50\": 0.5422, \"Box mAP50\": 0.5903, \"OOD mAP50\": 0.0944},\n",
        "    \"09_focal (Focal Mask-KL)\": {\"Mask mAP50\": 0.5413, \"Box mAP50\": 0.5847, \"OOD mAP50\": 0.0931},\n",
        "}\n",
        "\n",
        "# Dynamic scan for sibling JSON result files\n",
        "results_dirs = [Path(\"/kaggle/working/results\"), Path(\"results\"), Path(\"/kaggle/input\")]\n",
        "for rdir in results_dirs:\n",
        "    if rdir.exists():\n",
        "        for jf in rdir.glob(\"**/*.json\"):\n",
        "            if jf.name.startswith(\"exp_\") or jf.name.startswith(\"prod_\"):\n",
        "                try:\n",
        "                    with open(jf) as f:\n",
        "                        d = json.load(f)\n",
        "                    exp_k = d.get(\"experiment\", jf.stem)\n",
        "                    m_in = d.get(\"metrics_indomain\", {})\n",
        "                    m_ood = d.get(\"metrics_ood\", {})\n",
        "                    if \"mask_mAP50\" in m_in:\n",
        "                        BASELINES[f\"Live: {exp_k}\"] = {\n",
        "                            \"Mask mAP50\": float(m_in.get(\"mask_mAP50\", 0.0)),\n",
        "                            \"Box mAP50\": float(m_in.get(\"box_mAP50\", 0.0)),\n",
        "                            \"OOD mAP50\": float(m_ood.get(\"ood_mask_mAP50\", 0.0)) if \"ood_mask_mAP50\" in m_ood else 0.0\n",
        "                        }\n",
        "                except Exception:\n",
        "                    pass\n",
        "\n",
        "best_pt = glob.glob(f\"runs/**/{EXPERIMENT_NAME}*/weights/best.pt\", recursive=True)\n",
        "assert best_pt, f\"No checkpoint found for {EXPERIMENT_NAME}! Check run directory.\"\n",
        "\n",
        "print(f\"Evaluating best checkpoint: {best_pt[0]}\")\n",
        "model = YOLO(best_pt[0])\n",
        "\n",
        "# 1. Validate on Crack500 In-Domain Val Set\n",
        "print(\"\\n--- In-Domain Cropped Validation ---\")\n",
        "val_metrics = model.val(data=\"data/datasets/crack500_yolo/dataset.yaml\", split=\"val\", verbose=True)\n",
        "mask_map50 = float(val_metrics.seg.map50)\n",
        "mask_map95 = float(val_metrics.seg.map)\n",
        "box_map50  = float(val_metrics.box.map50)\n",
        "box_map95  = float(val_metrics.box.map)\n",
        "\n",
        "results = {\n",
        "    \"experiment\": EXPERIMENT_NAME,\n",
        "    \"seed\": 42,\n",
        "    \"checkpoint\": best_pt[0],\n",
        "    \"metrics_indomain\": {\n",
        "        \"mask_mAP50\": mask_map50,\n",
        "        \"mask_mAP50_95\": mask_map95,\n",
        "        \"box_mAP50\": box_map50,\n",
        "        \"box_mAP50_95\": box_map95,\n",
        "        \"mask_precision\": float(val_metrics.seg.p[0]) if hasattr(val_metrics.seg, \"p\") and len(val_metrics.seg.p) > 0 else float(val_metrics.seg.mp),\n",
        "        \"mask_recall\": float(val_metrics.seg.r[0]) if hasattr(val_metrics.seg, \"r\") and len(val_metrics.seg.r) > 0 else float(val_metrics.seg.mr)\n",
        "    }\n",
        "}\n",
        "\n",
        "# 2. Validate on Crack500 Uncropped (OOD) Set\n",
        "ood_mask_map50 = None\n",
        "uncropped_yaml = Path(\"data/datasets/crack500_uncropped_yolo/dataset.yaml\")\n",
        "if uncropped_yaml.exists():\n",
        "    print(\"\\n--- Out-of-Distribution (Uncropped) Validation ---\")\n",
        "    ood_metrics = model.val(data=str(uncropped_yaml), split=\"val\", verbose=True)\n",
        "    ood_mask_map50 = float(ood_metrics.seg.map50)\n",
        "    results[\"metrics_ood\"] = {\n",
        "        \"ood_mask_mAP50\": ood_mask_map50,\n",
        "        \"ood_mask_mAP50_95\": float(ood_metrics.seg.map),\n",
        "        \"ood_box_mAP50\": float(ood_metrics.box.map50),\n",
        "        \"ood_box_mAP50_95\": float(ood_metrics.box.map)\n",
        "    }\n",
        "else:\n",
        "    print(\"Warning: Uncropped dataset.yaml not found — skipping OOD evaluation.\")\n",
        "\n",
        "print(\"\\n\" + \"=\"*72)\n",
        "print(f\"📊 HEAD-TO-HEAD COMPARISON vs. EXISTING BASELINES\")\n",
        "print(\"=\"*72)\n",
        "print(f\"  {'Model':<36} {'In-Domain Mask':>16} {'OOD Mask':>12} {'Box mAP50':>12}\")\n",
        "print(\"-\"*72)\n",
        "for name, vals in BASELINES.items():\n",
        "    ood_val = f\"{vals['OOD mAP50']:>12.4f}\" if vals.get('OOD mAP50') is not None else f\"{'N/A':>12}\"\n",
        "    print(f\"  {name:<36} {vals['Mask mAP50']:>16.4f} {ood_val} {vals['Box mAP50']:>12.4f}\")\n",
        "print(\"-\"*72)\n",
        "ood_str = f\"{ood_mask_map50:>12.4f}\" if ood_mask_map50 is not None else f\"{'N/A':>12}\"\n",
        "print(f\"  {'⭐ COMBINED AFFINITY + DILATED':<36} {mask_map50:>16.4f} {ood_str} {box_map50:>12.4f}  ← THIS RUN\")\n",
        "print(\"=\"*72)\n",
        "\n",
        "best_indomain_key = max(BASELINES, key=lambda k: BASELINES[k]['Mask mAP50'])\n",
        "best_indomain_val = BASELINES[best_indomain_key]['Mask mAP50']\n",
        "delta_base = mask_map50 - 0.5400\n",
        "delta_best = mask_map50 - best_indomain_val\n",
        "print(f\"  vs. Baseline (0.5400)               : {delta_base:+.4f} ({delta_base/0.5400*100:+.1f}%)\")\n",
        "print(f\"  vs. Best In-Domain ({best_indomain_key[:18]}={best_indomain_val:.4f}): {delta_best:+.4f} ({delta_best/best_indomain_val*100:+.1f}%)\")\n",
        "if ood_mask_map50 is not None:\n",
        "    delta_ood_base = ood_mask_map50 - 0.0848\n",
        "    delta_ood_dil  = ood_mask_map50 - 0.1007\n",
        "    print(f\"  OOD vs. Baseline (0.0848)           : {delta_ood_base:+.4f} ({delta_ood_base/0.0848*100:+.1f}%)\")\n",
        "    print(f\"  OOD vs. 03_dilated (0.1007)         : {delta_ood_dil:+.4f} ({delta_ood_dil/0.1007*100:+.1f}%)\")\n",
        "print()\n",
        "\n",
        "out_file = Path(f\"/kaggle/working/results/{EXPERIMENT_NAME}.json\")\n",
        "out_file.parent.mkdir(parents=True, exist_ok=True)\n",
        "with open(out_file, \"w\") as f:\n",
        "    json.dump(results, f, indent=2)\n",
        "print(f\"Saved structured summary to {out_file}\")\n"
    ]

    with open(dst_path, "w") as f:
        json.dump(nb, f, indent=1)
    print(f"Successfully generated {dst_path} (size: {dst_path.stat().st_size} bytes)")

if __name__ == "__main__":
    main()
